apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bono-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: bono
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
