apiVersion: v1
kind: Service
metadata:
  name: bono
spec:
  # clusterIP: None
  type: NodePort
  ports:
  - name: "3478"
    port: 3478
    nodePort: 30001
  - name: "5060"
    port: 5060
    nodePort: 30002
  - name: "5062"
    port: 5062
    nodePort: 30003
  selector:
    service: bono
